config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'

  resources :blogposts

  root 'blogposts#index'

  get 'pages/about' => 'pages#about'

  resources :messages, only: [:new, :create]

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
  def myupdate(params)
    if params[:category]
        cleaned_up_category = params[:category].join(' ')
    end
    update params
    self.category = cleaned_up_category
    self.save
  end
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :subject, :content
  validates :name, :email, :subject, :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def download
    send_file "#{RAILS_ROOT}/assets/#{params[:JoshuaToyResume]}", :type=>"text/pdf"
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: ENV['LOGIN'], except: [:index, :show]
  before_action :set_blogpost, only: [:show, :edit, :update, :destroy]

  # GET /blogposts
  # GET /blogposts.json
  def index
    @blogposts = Blogpost.all
  end

  # GET /blogposts/1
  # GET /blogposts/1.json
  def show
  end

  # GET /blogposts/new
  def new
    @blogpost = Blogpost.new
  end

  # GET /blogposts/1/edit
  def edit
  end

  # POST /blogposts
  # POST /blogposts.json
  def create
    @blogpost = Blogpost.new(blogpost_params)

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully created.' }
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogposts/1
  # PATCH/PUT /blogposts/1.json
  def update
    respond_to do |format|
      if @blogpost.myupdate(blogpost_params)
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogposts/1
  # DELETE /blogposts/1.json
  def destroy
    @blogpost.destroy
    respond_to do |format|
      format.html { redirect_to blogposts_url, notice: 'Blogpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogpost
      @blogpost = Blogpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogpost_params
      params.require(:blogpost).permit(:title, :body, :category => [])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.message_me(@message).deliver_now
      redirect_to new_message_path, notice: "Thank you for your message."
    else
      render :new
    end
  end

    private

    def message_params
      params.require(:message).permit(:name, :email, :subject, :content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogposts/_form.html.erb
<%= form_for(@blogpost) do |f| %>
  <% if @blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul>
      <% @blogpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.cktext_area :body %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, ['Miscellaneous','Design','RubyonRails','Javascript','Wordpress','Work','Education', 'PHP','Miscellaneous'],{prompt: "SELECT RELEVANT TAGS:"}, {:multiple => true, class: "form-control"} %>
  </div>
  <div class="actions" style="padding-top: 15px;">
    <%= f.submit :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/blogposts/_randomquote.html.erb
<%= @randomquote = [
  "\"Wisdom cannot be imparted. Wisdom that a wise man attempts to impart always sounds like foolishness to someone else ... Knowledge can be communicated, but not wisdom. One can find it, live it, do wonders through it, but one cannot communicate and teach it.\" ― Hermann Hesse, Siddhartha",
  "\"It is not for me to judge another man's life. I must judge, I must choose, I must spurn, purely for myself. For myself, alone.\" ― Hermann Hesse, Siddhartha",
  "\"Words do not express thoughts very well. they always become a little different immediately they are expressed, a little distorted, a little foolish. And yet it also pleases me and seems right that what is of value and wisdom to one man seems nonsense to another.\" ― Hermann Hesse, Siddhartha",
  "\"That's my secret, Captain: I'm always angry.\" ― Doctor Bruce Banner",
  "\"Sand is overrated. It's just tiny, little rocks.\" ― Eternal Sunshine of the Spotless Mind",
  "\"Data! Data! Data!” he cried impatiently. “I can’t make bricks without clay.\" ― Sherlock Holmes",
  "\"Roads? Where we're going, we don't need roads..\" ― Doc",
  "\"Strength does not come from physical capacity. It comes from an indomitable will.\" ― Mahatma Gandhi",
  "\"Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.\" ― Rick Osborne",
  "\"Milk is for babies. When you grow up you have to drink beer.\" ― Arnold Schwarzenegger",
  "\"Crisp and clean. No caffeine.\" ― RZA",
  "\"The beauty of quitting is, now that I've quit, I can have one, 'cause I've quit.\" ― Tom Waits",
  "\"When I let go of what I am, I become what I might be.\" ― 老子",
  "\"Nature does not hurry, yet everything is accomplished.\" ― 老子",
  "\"The secret of getting ahead is getting started.\" ― Mark Twain",
  "\"If you tell the truth, you don't have to remember anything.\" ― Mark Twain",
  "\"To read too many books is harmful.\" ― 毛泽东",
  "\"Men are born to succeed, not fail.\" ― Henry David Thoreau",
  "\"All our words from loose using have lost their edge.\" ― Ernest Hemingway",
  "\"Can I be excused for the rest of my life?\" ― SpongeBob",
  "\"Jerry, just remember, it’s not a lie if you believe it.\" ― George Costanza",
  "\"We all die. The goal isn't to live forever, the goal is to create something that will.\" ― Chuck Palahniuk",
  "\"I'm-a gonna get you!\" ― Mario",
  "\"When I’m in social situations I always hold onto my glass. It makes me feel comfortable and secure, and I don’t have to shake hands\" ― Larry David",
  "\"Always forgive your enemies; nothing annoys them so much.\" ― Oscar Wilde",
  "\" For those who exalt themselves will be humbled, and those who humble themselves will be exalted.\" ― Matthew 23:12",
  "\"I want you to be everything that's you, deep at the center of your being.\" ― 孔子",
  "\"Maybe someday we could become friends. Friends who ride majestic, translucent steeds, shooting flaming arrows across the bridge of Hemdale.\" ― Brennan, Step Brothers",
  "\"Now I’m in the limelight ’cause I rhyme tight.\" ― Biggie"
]
%>

app/views/blogposts/edit.html.erb
<h1>Editing Blogpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @blogpost %> |
<%= link_to 'Back', blogposts_path %>

app/views/blogposts/index.html.erb
<h1 class="page-header">What's Going on?</h1>

<div class="button-group filters-button-group text-center">
    <a href="#" class="category is-checked" data-filter="*">Show All</a>
    <a href="#" class="category" data-filter=".design">Design</a>
    <a href="#" class="category" data-filter=".rubyonrails">Ruby on Rails</a>
    <a href="#" class="category" data-filter=".javascript">Javascript</a>
    <a href="#" class="category" data-filter=".hotlink">Hotlink</a>
    <a href="#" class="category" data-filter=".work">Work</a>
    <a href="#" class="category" data-filter="numberGreaterThan50">Greater than 50</a>
    <a href="#" class="category" data-filter=".miscellaneous">Miscellaneous</a>
</div>

<div class="grid">
    <% @blogposts.each do |blogpost| %>
        <%= link_to blogpost do %>
            <div class="element-item <%= blogpost.category.downcase %>" data-category="rubyonrails">
              <h3 class="name"><%= blogpost.title %></h3>
              <p class="symbol">大龙</p>
              <p class="number"><%= blogpost.id.to_s.first(3) %></p>
              <p class="weight"><%= blogpost.created_at.strftime("%Y-%m-%d") %></p>
            </div>
        <% end %>
    <% end %>
</div>

app/views/blogposts/new.html.erb
<h1>New Blogpost</h1>

<%= render 'form' %>

<%= link_to 'Back', blogposts_path %>

app/views/blogposts/show.html.erb
<p id="notice"><%= notice %></p>

<article>
    <header>
        <h2><%= @blogpost.title %></h2>
    </header>

    <aside>
        <% render 'randomquote' %>
        <%= @randomquote.shuffle.first %>
    </aside>
    <%= @blogpost.body.html_safe %>
    <footer>
        Posted on <%= @blogpost.created_at.strftime("%A, %B %d, %Y at %H:%M") %>
        <br>
        <div class="tags clearfix">
        <% @blogpost.category.split.each do |tag| %>
                <div class="tag"><a href="#"><%= tag %></a></div>
            <% end %>
        </div>
    </footer>
</article>

<div class="button-spacer">
    <%= link_to 'Back', blogposts_path %>
</div>

app/views/layouts/_footer.html.erb
<style>
.original-container {
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
}
.text-center.original-container{
    padding: 10px 30px;
}
.footer {
    bottom: 0;
}
</style>

<footer class="text-center">
    <span id="toymech">ToyMech Pro.</span>
    <div id="hiddentext" style="display: none">
        <div class="text-center original-container">
            "Siddhartha does nothing – he waits, he thinks, he fasts – but he passes through the things of the world like the stone through the water, without bestirring himself. He is drawn forward and he lets himself fall. His goal draws himself to it, for he lets nothing enter his mind that interferes with the goal."
        </div>
    </div>
</footer>

<script>
    $( "#toymech" ).click(function() {
        $( "#hiddentext" ).toggle();
    });

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-78150126-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_nav.html.erb
<nav class="menu" tabindex="0">
    <div class="smartphone-menu-trigger"></div>
    <header class="avatar">
        <%= image_tag "jtoy4.png", style: "background-color: #fff;" %>
        <h2>Joshua Toy</h2>
    </header>
    <ul class="menu-items">
        <li tabindex="0">
            <i class="fa fa-home" aria-hidden="true"></i>
            <span><%= link_to 'Home', root_path %></span>
        </li>
        <li tabindex="0">
            <i class="fa fa-envelope" aria-hidden="true"></i>
            <span><%= link_to 'Contact', messages_new_path %></span></span>
        </li>
        <li tabindex="0">
            <i class="fa fa-user" aria-hidden="true"></i>
            <span><%= link_to 'About', pages_about_path %></span>
        </li>
        <li tabindex="0">
            <i class="fa fa-file" aria-hidden="true"></i>
            <span><%= link_to 'Resumé', asset_path('JoshuaToysResume.pdf'), target:"_blank" %></span>
        </li>
        <br>
        <li tabindex="0">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span><%= link_to 'Somatic', "http://somatic.io/", target:"_blank" %></span>
        </li>
        <li tabindex="0">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span><%= link_to 'The Dictator', "http://dictionary.bitballoon.com/", target:"_blank" %></span>
        </li>
        <li tabindex="0">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span><%= link_to 'Random Quotes', '#', target:"_blank" %></span>
        </li>
        <li tabindex="0">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span><%= link_to 'Calculator', 'http://jcalculator.bitballoon.com/', target:"_blank" %></span>
        </li>
        <li tabindex="0">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span><%= link_to 'Balern Edu. 伯伦教育', 'http://balern.herokuapp.com/', target:"_blank" %></span>
        </li>
        <li tabindex="0">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span><%= link_to 'Mickey\'s Fishing', 'http://mickeycunliffe.bitballoon.com/', target:"_blank" %></span>
        </li>
        <li tabindex="0">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span><%= link_to 'Random Quote', 'http://quotemachine.heroku.com/', target:"_blank" %></span>
        </li>
        <li tabindex="0">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span><%= link_to 'Wiki Clone', 'http://wikipediaclone.herokuapp.com/articles', target:"_blank" %></span>
        </li>
        <li tabindex="0">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span><%= link_to 'Tic Tac Toe', 'http://triplet.bitballoon.com/', target:"_blank" %></span>
        </li>

    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToyMechPro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="shortcut icon" href="/assets/favicon.ico" />
  <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-hQpvDQiCJaD2H465dQfA717v7lu5qHWtDbWNPvaTJ0ID5xnPUlVXnKzq7b8YUkbN" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<p id="notice"><%= notice %></p>

<main>
    <%= render 'layouts/nav' %>
    <div class="container">
        <%= yield %>
    </div>
</main>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/messages/new.html.erb
<style>
  *, *:before, *:after {
  box-sizing: border-box;
}

html {
  overflow-y: scroll;
}/*

body {
  background: #c1bdba;
  font-family: 'Titillium Web', sans-serif;
}

a {
  text-decoration: none;
  color: #1ab188;
  -webkit-transition: .5s ease;
  transition: .5s ease;
}
a:hover {
  color: #179b77;
}*/

.form {
  margin: 20px auto;
  padding: 40px 20px;
  width: 100%;
  min-height: 375px;
  background: #fff;
  border-radius: 6px;
  box-sizing: border-box;
/*  box-shadow: 6px 6px 2px rgba(0, 0, 0, 0.1);
*/}

.tab-group {
  list-style: none;
  padding: 0;
  margin: 0 0 40px 0;
}
.tab-group:after {
  content: "";
  display: table;
  clear: both;
}
.tab-group li a {
  display: block;
  text-decoration: none;
  padding: 15px;
  background: rgba(160, 179, 176, 0.25);
  color: #a0b3b0;
  font-size: 20px;
  float: left;
  width: 50%;
  text-align: center;
  cursor: pointer;
  -webkit-transition: .5s ease;
  transition: .5s ease;
}
.tab-group li a:hover {
  background: #179b77;
  color: #ffffff;
}
.tab-group .active a {
  background: #1ab188;
  color: #ffffff;
}

.tab-content > div:last-child {
  display: none;
}

/*h1 {
  text-align: center;
  color: #ffffff;
  font-weight: 300;
  margin: 0 0 40px;
}*/

label {
  position: absolute;
  -webkit-transform: translateY(6px);
          transform: translateY(6px);
  left: 13px;
  color: rgba(127, 140, 141, 0.9);
  -webkit-transition: all 0.25s ease;
  transition: all 0.25s ease;
  -webkit-backface-visibility: hidden;
  pointer-events: none;
  font-size: 22px;
}
label .req {
  margin: 2px;
  color: #1ab188;
}

label.active {
  -webkit-transform: translateY(50px);
          transform: translateY(50px);
  left: 2px;
  font-size: 14px;
}
label.active .req {
  opacity: 0;
}

label.highlight {
  color: #ffffff;
}

input, textarea {
  font-size: 22px;
  display: block;
  width: 100%;
  height: 100%;
  padding: 5px 10px;
  background: none;
  background-image: none;
  border: 1px solid #a0b3b0;
  color: #666;
  border-radius: 0;
  -webkit-transition: border-color .25s ease, box-shadow .25s ease;
  transition: border-color .25s ease, box-shadow .25s ease;
}
input:focus, textarea:focus {
  outline: 0;
  border-color: #1ab188;
}

textarea {
  border: 2px solid #a0b3b0;
  resize: vertical;
}

.field-wrap {
  position: relative;
  margin-bottom: 40px;
}

.top-row:after {
  content: "";
  display: table;
  clear: both;
}
.top-row > div {
  float: left;
  width: 48%;
  margin-right: 4%;
}
.top-row > div:last-child {
  margin: 0;
}/*

.button {
  border: 0;
  outline: none;
  border-radius: 0;
  padding: 15px 0;
  font-size: 2rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: .1em;
  background: #1ab188;
  color: #ffffff;
  -webkit-transition: all 0.5s ease;
  transition: all 0.5s ease;
  -webkit-appearance: none;
}
.button:hover, .button:focus {
  background: #179b77;
}

.button-block {
  display: block;
  width: 100%;
}*/

.forgot {
  margin-top: -20px;
  text-align: right;
}


</style>
<div class="form">

      <ul class="tab-group">
        <li class="tab active"><a href="#signup">Business</a></li>
        <li class="tab"><a href="#login">Pleasure</a></li>
      </ul>

    <div class="tab-content">
        <div id="signup">
            <h1>Contact Me Directly</h1>
                <%= form_for @message do |f| %>
                  <% if @message.errors.any? %>
                    <div id="error_explanation">
                      <h2>
                        <%= "#{pluralize(@message.errors.count, "error")} prohibited this message from being sent:" %>
                      </h2>

                      <ul>
                        <% @message.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                      <ul>
                    </div>
                  <% end %>

                  <div class="field-wrap field">
                    <%= f.label :name %>
                    <%= f.text_field :name %>
                  </div>

                  <div class="field-wrap field">
                    <%= f.label :email %>
                    <%= f.email_field :email %>
                  </div>

                  <div class="field-wrap field">
                    <%= f.label :subject %>
                    <%= f.text_field :subject %>
                  </div>

                  <div class="field-wrap field">
                    <%= f.label :content %>
                    <%= f.text_area :content %>
                  </div>

                  <div class="actions">
                    <%= f.submit 'Send', class: 'btn btn-primary btn-lg btn-theme btn-block' %>
                  </div>
                <% end %>
        </div>

        <div id="login">
            <h1>Follow Me Online:</h1>

            <div class="set rounded tilted text-center">
              <a href="https://www.facebook.com/profile.php?id=100010668903210" class="social facebook">Facebook</a>
              <a href="https://twitter.com/JoshuaToys" class="social twitter">Twitter</a>
              <a href="http://codepen.io/toymechqm/" class="social codepen">Codepen</a>
              <a href="https://bitbucket.org/ToyMechQM/" class="social bitbucket">Stripe</a>
              <a href="#" class="pop social wechat">Wechat</a>
              <a href="https://github.com/toymechqm/" class="social github">Github</a>
            </div>


            <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body text-center">
                            <button type="button" class="close" data-dismiss="modal">   <span aria-hidden="true">&times;</span>
                                <span class="sr-only">Close</span>
                            </button>
                            <%= image_tag('qr.png') %>
                        </div>
                    </div>
                </div>
            </div>

            <h3>Get on The Mailing List</h3>
            <form action="/" method="post">
                <div class="field-wrap">
                    <label>
                      Email Address<span class="req">*</span>
                    </label>
                    <input type="email"required autocomplete="off"/>
                </div>
                <button class="btn btn-primary btn-lg btn-theme btn-block"/>Subscribe</button>
            </form>

        </div>

      </div><!-- tab-content -->

</div> <!-- /form -->
<script>
  $('.form').find('input, textarea').on('keyup blur focus', function (e) {

  var $this = $(this),
      label = $this.prev('label');

    if (e.type === 'keyup') {
      if ($this.val() === '') {
          label.removeClass('active highlight');
        } else {
          label.addClass('active highlight');
        }
    } else if (e.type === 'blur') {
      if( $this.val() === '' ) {
        label.removeClass('active highlight');
      } else {
        label.removeClass('highlight');
      }
    } else if (e.type === 'focus') {

      if( $this.val() === '' ) {
        label.removeClass('highlight');
      }
      else if( $this.val() !== '' ) {
        label.addClass('highlight');
      }
    }

});

$('.tab a').on('click', function (e) {

  e.preventDefault();

  $(this).parent().addClass('active');
  $(this).parent().siblings().removeClass('active');

  target = $(this).attr('href');

  $('.tab-content > div').not(target).hide();

  $(target).fadeIn(600);

});

$(function() {
    $('.pop').on('click', function() {
      $('.imagepreview').attr('src', $(this).find('img').attr('src'));
      $('#imagemodal').modal('show');
    });
});
</script>

app/views/pages/about.html.erb
<style>
.text-block{
    padding-top: 50px;
}
.about-font{
    font-size: 15px;
    line-height: 1.5em;
}

article {
    margin-left: 3%;
}

}
article, .lable-head, .label-name {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
.vcard {
    width: 300px; height: 200px;
    background: #e00;
    border-radius: 10px;
    box-shadow: 1px 2px 5px rgba(0,0,0,.5), inset 0 0 20px rgba(0,0,0,.25);
    -webkit-transform: rotate(-10deg);
    -moz-transform: rotate(-10deg);
    transform: rotate(-10deg);
}
.vcard div:first-child {
    height: 65px;
    padding-top: 5px;
    color: #fff;
    font-family: Helvetica, Arial, sans-serif;
    text-transform: uppercase;
    text-align: center;
    letter-spacing: .2em;
}
h1 {
    padding: 0; margin: 0;
    font-size: 2em;
}

.fn {
    background: #fff;
    height: 120px;
    font-family: "Coming Soon", "Comic Sans MS", cursive;
    text-align: center;
    padding-top: 5px;
}
.given-name {
    font-size: 3em;
    font-weight: bold;
}
.nickname {
    font-size: 1.5em;
    font-weight: bold;
    font-style: normal;
}
.mni{
  color: #fff;
}
.hello{
  color: #fff;
  font-weight: 600;
}
</style>


<link rel="profile" href="http://microformats.org/profile/hcard">

<article class="vcard">
    <div>
        <h1 class="hello">Hello</h1>
        <p class="mni">my name is</p>
    </div>
    <div class="fn">
        <p class="given-name">Joshua</p>
        <address class="nickname">@JoshuaToys</address>
    </div>
</article>

<link href='http://fonts.googleapis.com/css?family=Coming+Soon' rel='stylesheet' type='text/css'>



<p class="about-font text-block">
    Currently I am a Web developer in Massachusetts working primarily with PHP. When my coding journey began I had zero experience with PHP, but in just a short space of time I’ve made quite a bit of progress. I’m responsible for handling our company’s online presence, managing our CRM, building and designing websites with PHP and JavaScript (or whatever other tools may be necessary), and implementing APIs. We even work with wordpress now and then, too.
</p>

<p class="about-font">
    While I enjoy working with Ruby and JavaScript, what I most enjoy is building tools, refactoring, designing beautiful things and making tasks easier through automation. I find a great satisfaction from taking a difficult task and making the process more time or energy efficient. To keep up with the latest and greatest technologies and best practices I am constantly building toy applications and attending conferences and meetups.
</p>

<p class="about-font">
    Beyond the world of web development, I love riding my Harley, traveling, learning traditional languages and playing games, and on a slow day you’ll probably catch me kicking back with a cup of tea and an episode of King of the Hill.
</p>